server:
  port: 8081

spring:
  application:
    # 服务名称
    name: user
  cloud:
    nacos:
      # nacos server的地址
      server-addr: localhost:8848
      discovery:
        namespace: bbe84747-9ee2-4256-b5e3-c79d9b14b885