server:
  port: 8082

spring:
  application:
    # 服务名称
    name: coupon
  cloud:
    nacos:
      # nacos server的地址
      server-addr: localhost:8848
      discovery:
        namespace: bbe84747-9ee2-4256-b5e3-c79d9b14b885
        group: member-group
        cluster-name: 上海

